/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 GrowPlay-4.glb --keepnames --keepgroups --keepmeshes --keepmaterials 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/GrowPlay-4.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty001" position={[-3.002, 0.346, -0.023]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="_Long_upright_right_end_front" geometry={nodes._Long_upright_right_end_front.geometry} material={materials['Silver metal dull']} position={[6.138, 1.173, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="a" geometry={nodes.a.geometry} material={materials['Material.001']} position={[-0.039, 1.226, -4.253]} />
        <mesh name="cross_piece_1" geometry={nodes.cross_piece_1.geometry} material={materials['Silver metal dull']} position={[-6.16, 0.53, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1001" geometry={nodes.cross_piece_1001.geometry} material={materials['Silver metal dull']} position={[-6.16, 1.114, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1002" geometry={nodes.cross_piece_1002.geometry} material={materials['Silver metal dull']} position={[-6.16, 1.846, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1003" geometry={nodes.cross_piece_1003.geometry} material={materials['Silver metal dull']} position={[-5.865, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1004" geometry={nodes.cross_piece_1004.geometry} material={materials['Silver metal dull']} position={[-4.989, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1005" geometry={nodes.cross_piece_1005.geometry} material={materials['Silver metal dull']} position={[-4.16, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1006" geometry={nodes.cross_piece_1006.geometry} material={materials['Silver metal dull']} position={[-3.226, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1007" geometry={nodes.cross_piece_1007.geometry} material={materials['Silver metal dull']} position={[-2.409, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1008" geometry={nodes.cross_piece_1008.geometry} material={materials['Silver metal dull']} position={[-1.735, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1009" geometry={nodes.cross_piece_1009.geometry} material={materials['Silver metal dull']} position={[-0.808, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1010" geometry={nodes.cross_piece_1010.geometry} material={materials['Silver metal dull']} position={[-0.011, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1011" geometry={nodes.cross_piece_1011.geometry} material={materials['Silver metal dull']} position={[0.67, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1012" geometry={nodes.cross_piece_1012.geometry} material={materials['Silver metal dull']} position={[1.694, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1013" geometry={nodes.cross_piece_1013.geometry} material={materials['Silver metal dull']} position={[2.413, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1014" geometry={nodes.cross_piece_1014.geometry} material={materials['Silver metal dull']} position={[3.126, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1015" geometry={nodes.cross_piece_1015.geometry} material={materials['Silver metal dull']} position={[4.027, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1016" geometry={nodes.cross_piece_1016.geometry} material={materials['Silver metal dull']} position={[4.779, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1017" geometry={nodes.cross_piece_1017.geometry} material={materials['Silver metal dull']} position={[5.603, 2.434, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1018" geometry={nodes.cross_piece_1018.geometry} material={materials['Silver metal dull']} position={[6.139, 2.011, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1019" geometry={nodes.cross_piece_1019.geometry} material={materials['Silver metal dull']} position={[6.139, 1.419, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="cross_piece_1020" geometry={nodes.cross_piece_1020.geometry} material={materials['Silver metal dull']} position={[6.139, 0.526, -0.022]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Elbow_piece" geometry={nodes.Elbow_piece.geometry} material={nodes.Elbow_piece.material} position={[6.067, 2.427, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Elbow_piece001" geometry={nodes.Elbow_piece001.geometry} material={nodes.Elbow_piece001.material} position={[6.067, 2.427, -0.467]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Elbow_piece002" geometry={nodes.Elbow_piece002.geometry} material={nodes.Elbow_piece002.material} position={[-6.094, 2.427, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Elbow_piece003" geometry={nodes.Elbow_piece003.geometry} material={nodes.Elbow_piece003.material} position={[-6.101, 2.427, -0.467]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Foot_cup" geometry={nodes.Foot_cup.geometry} material={materials['Silver metal dull']} position={[6.137, 0, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Foot_cup001" geometry={nodes.Foot_cup001.geometry} material={materials['Silver metal dull']} position={[6.137, 0, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Foot_cup006" geometry={nodes.Foot_cup006.geometry} material={materials['Silver metal dull']} position={[-6.161, 0, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Foot_cup007" geometry={nodes.Foot_cup007.geometry} material={materials['Silver metal dull']} position={[-6.161, 0, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="g" geometry={nodes.g.geometry} material={materials['Material.001']} position={[-0.039, 1.046, 2.56]} />
        <mesh name="Joiner_sleeve3" geometry={nodes.Joiner_sleeve3.geometry} material={materials['Silver metal dull']} position={[-1.237, 2.43, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Joiner_sleeve3001" geometry={nodes.Joiner_sleeve3001.geometry} material={materials['Silver metal dull']} position={[-3.695, 2.43, -0.475]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Joiner_sleeve3002" geometry={nodes.Joiner_sleeve3002.geometry} material={materials['Silver metal dull']} position={[1.153, 2.43, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Joiner_sleeve3003" geometry={nodes.Joiner_sleeve3003.geometry} material={materials['Silver metal dull']} position={[3.602, 2.43, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Joiner_sleeve3004" geometry={nodes.Joiner_sleeve3004.geometry} material={materials['Silver metal dull']} position={[-3.695, 2.43, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Joiner_sleeve3005" geometry={nodes.Joiner_sleeve3005.geometry} material={materials['Silver metal dull']} position={[1.153, 2.43, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Joiner_sleeve3006" geometry={nodes.Joiner_sleeve3006.geometry} material={materials['Silver metal dull']} position={[3.602, 2.43, -0.47]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="l-L" geometry={nodes['l-L'].geometry} material={materials['Material.001']} position={[-0.039, 1.455, -3.354]} />
        <mesh name="logo_dark_green" geometry={nodes.logo_dark_green.geometry} material={materials['dark green']} position={[-0.039, 1.216, 4.758]} />
        <mesh name="logo_light_green" geometry={nodes.logo_light_green.geometry} material={materials['light green']} position={[-0.039, 1.216, 4.758]} />
        <mesh name="logo_yellow" geometry={nodes.logo_yellow.geometry} material={materials.yellow} position={[-0.039, 1.216, 4.758]} />
        <mesh name="Long_upright_left_end_front" geometry={nodes.Long_upright_left_end_front.geometry} material={materials['Silver metal dull']} position={[-6.16, 1.173, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_left_end_rear" geometry={nodes.Long_upright_left_end_rear.geometry} material={materials['Silver metal dull']} position={[-6.16, 1.173, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_left_top_front" geometry={nodes.Long_upright_left_top_front.geometry} material={materials['Silver metal dull']} position={[-4.911, 2.43, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_left_top_rear" geometry={nodes.Long_upright_left_top_rear.geometry} material={materials['Silver metal dull']} position={[-4.911, 2.43, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_middle_top_front" geometry={nodes.Long_upright_middle_top_front.geometry} material={materials['Silver metal dull']} position={[0.009, 2.43, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_middle_top_rear" geometry={nodes.Long_upright_middle_top_rear.geometry} material={materials['Silver metal dull']} position={[0.009, 2.43, -0.47]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_right_end_rear" geometry={nodes.Long_upright_right_end_rear.geometry} material={materials['Silver metal dull']} position={[6.138, 1.173, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_right_top_front" geometry={nodes.Long_upright_right_top_front.geometry} material={materials['Silver metal dull']} position={[4.849, 2.43, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_right_top_rear" geometry={nodes.Long_upright_right_top_rear.geometry} material={materials['Silver metal dull']} position={[4.849, 2.43, -0.47]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_second_left_top_front" geometry={nodes.Long_upright_second_left_top_front.geometry} material={materials['Silver metal dull']} position={[-2.449, 2.43, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_second_left_top_rear" geometry={nodes.Long_upright_second_left_top_rear.geometry} material={materials['Silver metal dull']} position={[-2.449, 2.43, -0.47]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_second_right_top_front" geometry={nodes.Long_upright_second_right_top_front.geometry} material={materials['Silver metal dull']} position={[2.4, 2.43, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Long_upright_second_right_top_rear" geometry={nodes.Long_upright_second_right_top_rear.geometry} material={materials['Silver metal dull']} position={[2.4, 2.43, -0.47]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="o" geometry={nodes.o.geometry} material={materials['Material.001']} position={[-0.039, 1.218, 0.536]} />
        <mesh name="p" geometry={nodes.p.geometry} material={materials['Material.001']} position={[-0.039, 1.215, -2.489]} />
        <mesh name="r" geometry={nodes.r.geometry} material={materials['Material.001']} position={[-0.039, 1.528, 1.403]} />
        <mesh name="t-piece_1" geometry={nodes['t-piece_1'].geometry} material={nodes['t-piece_1'].material} position={[-6.16, 0.529, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1001" geometry={nodes['t-piece_1001'].geometry} material={nodes['t-piece_1001'].material} position={[-6.16, 1.112, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1002" geometry={nodes['t-piece_1002'].geometry} material={nodes['t-piece_1002'].material} position={[-6.16, 1.844, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1003" geometry={nodes['t-piece_1003'].geometry} material={materials['Silver metal dull']} position={[-5.866, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1004" geometry={nodes['t-piece_1004'].geometry} material={nodes['t-piece_1004'].material} position={[-4.991, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1005" geometry={nodes['t-piece_1005'].geometry} material={nodes['t-piece_1005'].material} position={[-4.162, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1006" geometry={nodes['t-piece_1006'].geometry} material={nodes['t-piece_1006'].material} position={[-3.228, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1007" geometry={nodes['t-piece_1007'].geometry} material={nodes['t-piece_1007'].material} position={[-2.411, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1008" geometry={nodes['t-piece_1008'].geometry} material={nodes['t-piece_1008'].material} position={[-1.737, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1009" geometry={nodes['t-piece_1009'].geometry} material={nodes['t-piece_1009'].material} position={[-0.81, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1010" geometry={nodes['t-piece_1010'].geometry} material={nodes['t-piece_1010'].material} position={[-0.013, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1011" geometry={nodes['t-piece_1011'].geometry} material={nodes['t-piece_1011'].material} position={[0.668, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1012" geometry={nodes['t-piece_1012'].geometry} material={nodes['t-piece_1012'].material} position={[1.692, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1013" geometry={nodes['t-piece_1013'].geometry} material={nodes['t-piece_1013'].material} position={[2.411, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1014" geometry={nodes['t-piece_1014'].geometry} material={nodes['t-piece_1014'].material} position={[3.125, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1015" geometry={nodes['t-piece_1015'].geometry} material={nodes['t-piece_1015'].material} position={[4.026, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1016" geometry={nodes['t-piece_1016'].geometry} material={nodes['t-piece_1016'].material} position={[4.777, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1017" geometry={nodes['t-piece_1017'].geometry} material={nodes['t-piece_1017'].material} position={[5.601, 2.434, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1018" geometry={nodes['t-piece_1018'].geometry} material={nodes['t-piece_1018'].material} position={[6.139, 2.013, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1019" geometry={nodes['t-piece_1019'].geometry} material={nodes['t-piece_1019'].material} position={[6.139, 1.42, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_1020" geometry={nodes['t-piece_1020'].geometry} material={nodes['t-piece_1020'].material} position={[6.139, 0.527, 0.435]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2" geometry={nodes['t-piece_2'].geometry} material={nodes['t-piece_2'].material} position={[-6.16, 0.529, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2001" geometry={nodes['t-piece_2001'].geometry} material={nodes['t-piece_2001'].material} position={[-6.16, 1.112, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2002" geometry={nodes['t-piece_2002'].geometry} material={nodes['t-piece_2002'].material} position={[-6.16, 1.844, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2003" geometry={nodes['t-piece_2003'].geometry} material={nodes['t-piece_2003'].material} position={[-5.866, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2004" geometry={nodes['t-piece_2004'].geometry} material={nodes['t-piece_2004'].material} position={[-4.991, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2005" geometry={nodes['t-piece_2005'].geometry} material={nodes['t-piece_2005'].material} position={[-4.162, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2006" geometry={nodes['t-piece_2006'].geometry} material={nodes['t-piece_2006'].material} position={[-3.228, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2007" geometry={nodes['t-piece_2007'].geometry} material={nodes['t-piece_2007'].material} position={[-2.411, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2008" geometry={nodes['t-piece_2008'].geometry} material={nodes['t-piece_2008'].material} position={[-1.737, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2009" geometry={nodes['t-piece_2009'].geometry} material={nodes['t-piece_2009'].material} position={[-0.81, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2010" geometry={nodes['t-piece_2010'].geometry} material={nodes['t-piece_2010'].material} position={[-0.013, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2011" geometry={nodes['t-piece_2011'].geometry} material={nodes['t-piece_2011'].material} position={[0.668, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2012" geometry={nodes['t-piece_2012'].geometry} material={nodes['t-piece_2012'].material} position={[1.692, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2013" geometry={nodes['t-piece_2013'].geometry} material={nodes['t-piece_2013'].material} position={[2.411, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2014" geometry={nodes['t-piece_2014'].geometry} material={nodes['t-piece_2014'].material} position={[3.125, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2015" geometry={nodes['t-piece_2015'].geometry} material={nodes['t-piece_2015'].material} position={[4.026, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2016" geometry={nodes['t-piece_2016'].geometry} material={nodes['t-piece_2016'].material} position={[4.777, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2017" geometry={nodes['t-piece_2017'].geometry} material={nodes['t-piece_2017'].material} position={[5.601, 2.434, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2018" geometry={nodes['t-piece_2018'].geometry} material={nodes['t-piece_2018'].material} position={[6.139, 2.013, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2019" geometry={nodes['t-piece_2019'].geometry} material={nodes['t-piece_2019'].material} position={[6.139, 1.42, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="t-piece_2020" geometry={nodes['t-piece_2020'].geometry} material={nodes['t-piece_2020'].material} position={[6.139, 0.527, -0.468]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="w" geometry={nodes.w.geometry} material={materials['Material.001']} position={[-0.039, 1.233, -0.909]} />
        <mesh name="y" geometry={nodes.y.geometry} material={materials['Material.001']} position={[-0.039, 1.059, -5.463]} />
      </group>
    </group>
  )
}

useGLTF.preload('/GrowPlay-4.glb')
